<?php

namespace AppBundle\Repository;

/**
 * Cms_adminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cms_adminRepository extends \Doctrine\ORM\EntityRepository
{
}
