<?php

namespace AppBundle\Repository;

/**
 * Cms_menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cms_menuRepository extends \Doctrine\ORM\EntityRepository
{
}
