<?php

namespace AppBundle\Repository;

/**
 * Cms_menu_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cms_menu_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
