<?php

namespace AppBundle\Repository;

/**
 * Cms_postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cms_postRepository extends \Doctrine\ORM\EntityRepository
{
}
