<?php

namespace AppBundle\Repository;

/**
 * Cms_commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cms_commentRepository extends \Doctrine\ORM\EntityRepository
{
}
